name: Report a bug
description: Something doesn't work as expected?
title: "Bug: "
labels: ["bug"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what
    attributes:
      label: Describe the bug
      placeholder: A short description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: Detail the steps taken to reproduce the behavior.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: TinySemVer version
      placeholder: v2.0.0
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: false
  - type: checkboxes
    id: mentions
    attributes:
      label: Are you open to being tagged as a contributor?
      description: Sometimes a good bug report is just as valuable as a patch 🤗
      options:
        - label: I am open to being mentioned in the project `.git` history as a contributor
          required: false
  - type: checkboxes
    id: duplicate
    attributes:
      label: Is there an existing issue for this?
      description: Please search [our issues](https://github.com/ashvardanian/tinysemver/issues) to see if this bug already exists.
      options:
        - label: I have searched the existing issues
          required: true
